package coffee.cafeordersystem.CatalogItems;

public enum Ingredients {
    COFFEE_BEAN, DECAF_COFFEE_BEAN, TEA_LEAVES_BLACK, TEA_LEAVES_GREEN, TEA_LEAVES_HERBAL,
    DECAF_TEA_LEAVES_BLACK, DECAF_TEA_LEAVES_GREEN, SUGAR, FLOUR, BUTTER, CHOCOLATE_CHIP,
    ALMOND, ALMOND_MILK, OATMEAL, OAT_MILK, SUGAR_FREE_SYRUP, RAISIN, STRAWBERRY, BLUEBERRY,
    MILK
}